const DATE_FORMAT = 'YYYY-MM-DD';
const DATETIME_FORMAT = 'YYYY-MM-DD HH:mm:ss';
const TIME_FORMAT = 'HH:mm:ss';
const TIME_FORMAT_SHORT = 'HH:mm';
const TIME_FORMAT_MILLS = 'HH:mm:ss.SSS';
const SIMPLE_TIME_FORMAT_WITH_MILLISECOND = 'YYYY-MM-DD HH:mm:ss.SSS';

export {
  DATETIME_FORMAT,
  DATE_FORMAT,
  SIMPLE_TIME_FORMAT_WITH_MILLISECOND,
  TIME_FORMAT,
  TIME_FORMAT_MILLS,
  TIME_FORMAT_SHORT
};
